import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faDownload, faEdit, faCheckCircle, faSpinner, faPrint, faWallet, faMapPin, faCopy } from '@fortawesome/free-solid-svg-icons';
import { redraftTripPlan } from '../../services/gemini';
import useAppStore from '../../stores/useAppStore';
import TripPDFDocument from './TripPDFDocument';
import ItineraryRouteMap from './ItineraryRouteMap';
import html2pdf from 'html2pdf.js';


export default function TripOutput({ plan, setPlan, params = null, selectedHotel = null }) {
  const [isEditing, setIsEditing] = useState(false);
  const [instruction, setInstruction] = useState('');
  const [loading, setLoading] = useState(false);
  const { addToast } = useAppStore();
  const printRef = useRef();
  const navigate = useNavigate();

  if (!plan) return null;

  const handleCopyItinerary = () => {
    try {
      const days = plan.days || [];
      const lines = [
        `==================================================`,
        `📍 TRIP ITINERARY: ${plan.trip_name || 'Travel Itinerary'}`,
        `Destinations: ${(plan.destinations || []).join(', ')}`,
        `Dates: ${plan.from_date || ''} to ${plan.to_date || ''} (${plan.total_days || days.length} Days)`,
        `Estimated Total: ₹${(plan.trip_summary?.total_cost_inr || plan.estimated_budget_inr?.min || 0).toLocaleString('en-IN')}`,
        `==================================================\n`
      ];

      days.forEach(d => {
        lines.push(`--------------------------------------------------`);
        lines.push(`📅 DAY ${d.day}: ${d.theme || d.title || ''} (${d.city || ''}) - Date: ${d.date || ''}`);
        if (d.hotel?.name) {
          lines.push(`🏨 Hotel: ${d.hotel.name} (₹${d.hotel.price_per_night_inr || d.hotel.price || 0}/night)`);
        }
        lines.push(`\nSchedule:`);
        (d.schedule || d.activities || []).forEach(s => {
          const src = s.source === 'user' ? '[Your Choice] ' : '';
          const cost = s.cost_inr ? ` (₹${s.cost_inr})` : '';
          lines.push(`  • ${s.time || ''} - ${src}${s.place || s.name || ''}: ${s.activity || ''}${cost}`);
          if (s.notes) lines.push(`    ℹ️ Note: ${s.notes}`);
        });
        lines.push(`Est. Day Total: ₹${(d.day_total_inr || d.estimated_cost_inr || 0).toLocaleString('en-IN')}\n`);
      });

      lines.push(`Generated by PackUrBag AI Travel Planner (www.packurbag.in)`);

      navigator.clipboard.writeText(lines.join('\n'));
      addToast({ type: 'success', title: 'Copied!', message: 'Complete itinerary copied to clipboard.' });
    } catch (err) {
      console.error('Clipboard copy failed:', err);
      addToast({ type: 'error', message: 'Failed to copy text to clipboard.' });
    }
  };

  const handleRedraft = async () => {
    if (!instruction) return;
    setLoading(true);
    try {
      const updated = await redraftTripPlan(plan, instruction);
      if (updated.error) {
        addToast({ type: 'error', message: updated.error });
      } else {
        setPlan(updated);
        addToast({ type: 'success', message: 'Itinerary updated based on your instructions.' });
        setIsEditing(false);
        setInstruction('');
      }
    } catch (err) {
      addToast({ type: 'error', message: err.message });
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = async () => {
    const el = printRef.current;
    if (!el) { window.print(); return; }

    try {
      // Temporarily force desktop width so mobile/tablet gets a clean A4 PDF
      const originalStyle = el.style.cssText;
      el.style.width = '960px';
      el.style.maxWidth = '960px';

      const opt = {
        margin:       [8, 8, 8, 8], // mm: top/right/bottom/left
        filename:     'trip-itinerary.pdf',
        image:        { type: 'jpeg', quality: 0.97 },
        html2canvas:  {
          scale: 2,           // 2x for crisp text on all screens
          useCORS: true,
          logging: false,
          width: 960,
          windowWidth: 960,
        },
        jsPDF: {
          unit: 'mm',
          format: 'a4',
          orientation: 'portrait',
        },
        pagebreak: { mode: ['avoid-all', 'css'] },
      };

      await html2pdf().set(opt).from(el).save();

      // Restore original styles
      el.style.cssText = originalStyle;
    } catch (err) {
      console.error('PDF generation failed, falling back to print:', err);
      window.print();
    }
  };


  const handleProceedToBooking = () => {
    const locList = (params?.locations || plan?.destinations || ['Destination'])
      .toString()
      .split(',')
      .map(s => s.trim())
      .filter(Boolean);
    const toCity = locList[0] || 'Destination';
    const travelMode = params?.mode?.toLowerCase().includes('flight') ? 'flight' : 'bus';
    
    const queryParams = new URLSearchParams({
      type: travelMode,
      from: 'Delhi',
      to: toCity,
      fromDate: params?.fromDate || plan?.from_date || '',
      toDate: params?.toDate || plan?.to_date || '',
    });

    if (selectedHotel) {
      queryParams.append('hotelId', selectedHotel.hotel_id || 'selected');
      queryParams.append('hotelName', selectedHotel.name);
      queryParams.append('hotelPrice', (selectedHotel.price_per_night_inr || selectedHotel.price_inr || 0).toString());
    } else if (plan?.days?.[0]?.hotel?.name) {
      const hotel = plan.days[0].hotel;
      if (hotel.name && hotel.name !== 'null' && hotel.name !== 'N/A') {
        queryParams.append('hotelId', hotel.hotel_id || 'ai-selected');
        queryParams.append('hotelName', hotel.name);
        queryParams.append('hotelPrice', (hotel.price_per_night_inr || hotel.price || 0).toString());
      }
    }

    navigate(`/booking-grid?${queryParams.toString()}`);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      
      {/* Top Floating Action Bar (Images 2 & 3) */}
      <div className="bg-white rounded-3xl p-4 sm:p-5 shadow-sm border border-gray-200/90 flex flex-wrap gap-4 items-center justify-between no-print">
        <button 
          onClick={() => window.location.href = '/schedule-trip'}
          className="bg-white hover:bg-gray-50 text-gray-700 text-xs font-bold py-2.5 px-4 rounded-xl border border-gray-200 shadow-2xs flex items-center gap-2 transition-all cursor-pointer"
        >
          <span className="text-gray-400">←</span>
          <span>Back to Planning Experience</span>
        </button>

        <div className="flex flex-wrap items-center gap-2.5">
          <button 
            onClick={handleCopyItinerary} 
            className="px-4 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-800 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer shadow-2xs"
            title="Copy entire formatted itinerary to clipboard"
          >
            <FontAwesomeIcon icon={faCopy} className="text-[#f97316]" />
            <span>Copy Itinerary</span>
          </button>

          <button 
            onClick={() => setIsEditing(!isEditing)} 
            className="px-4 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer"
          >
            <FontAwesomeIcon icon={faEdit} className="text-[#f97316]" />
            <span>AI Redraft</span>
          </button>

          <button 
            onClick={handlePrint} 
            className="px-6 py-2.5 bg-[#f97316] hover:bg-[#ea580c] text-white rounded-xl text-xs font-black transition-all shadow-md hover:shadow-lg flex items-center gap-2 cursor-pointer"
          >
            <span>Download PDF</span>
            <FontAwesomeIcon icon={faDownload} />
          </button>

          <button 
            onClick={handleProceedToBooking} 
            className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold transition-all shadow-md flex items-center gap-1.5 cursor-pointer"
          >
            <FontAwesomeIcon icon={faWallet} />
            <span>Book &amp; Pay</span>
          </button>
        </div>
      </div>

      <AnimatePresence>
        {isEditing && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden no-print"
          >
            <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 mb-6">
              <h4 className="font-bold text-blue-900 mb-2">Refine Itinerary with AI</h4>
              <p className="text-sm text-blue-700 mb-4">Tell us what to change (e.g., "Make it more relaxed", "Add more food options", "Swap day 1 and 2")</p>
              <div className="flex gap-2">
                <input 
                  type="text" 
                  value={instruction}
                  onChange={e => setInstruction(e.target.value)}
                  placeholder="Your instructions..."
                  className="flex-1 px-4 py-2 rounded-xl border border-blue-200 outline-none focus:ring-2 ring-blue-400"
                />
                <button 
                  onClick={handleRedraft}
                  disabled={loading || !instruction}
                  className="bg-blue-600 text-white px-6 py-2 rounded-xl font-medium hover:bg-blue-700 disabled:bg-blue-400"
                >
                  {loading ? <FontAwesomeIcon icon={faSpinner} spin /> : 'Apply'}
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Printable Area */}
      <div 
        ref={printRef} 
        className="bg-white rounded-3xl p-8 shadow-xl print:shadow-none print:p-0 select-text cursor-text"
        style={{ userSelect: 'text', WebkitUserSelect: 'text' }}
      >
        <TripPDFDocument plan={plan} />
      </div>

      <div className="bg-white rounded-3xl p-6 shadow-xl mt-6 no-print">
        <h3 className="text-xl font-bold mb-4 text-gray-900 font-display flex items-center gap-2">
          <FontAwesomeIcon icon={faMapPin} className="text-[#D4B15A]" /> Live Route Map (Hotels & Spots)
        </h3>
        <ItineraryRouteMap 
          plan={plan} 
          fromCity={params?.fromCity || plan?.from_city || 'Delhi'}
          routeInfo={plan?.routeInfo}
          selectedHotel={selectedHotel}
          isVehicle={params?.mode?.toLowerCase().includes('vehicle') || params?.mode?.toLowerCase().includes('bike') || params?.mode?.toLowerCase().includes('drive') || plan?.travel_mode?.toLowerCase().includes('vehicle') || plan?.travel_mode?.toLowerCase().includes('drive') || plan?.travel_mode?.toLowerCase().includes('bike')}
          onCaptureSnippet={(data) => {
            setPlan(prev => ({ ...prev, liveMapSnippet: data }));
          }}
        />
      </div>

    </div>
  );
}
